### ISSUE TITLE
Review `metaschema-java`'s XML parser and implement an equivalent parser

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/metaschema-node#13]
As an OSCAL tool developer, I need the ability to serialize metaschema from valid, well-formed XML definitions into classes inheriting the `metaschema-model-common` core object model and back into XML.

This task can be decomposed into the following parts:
- [x] Implement a basic datatype and adapter (a subset of #7) for a basic metaschema type, such as a `string` type.
- [x] Research and choose an XML parser implementation with the features needed to parse complex metaschema documents
- [x] Create a bare metaschema parser with the capabilities needed to parse a basic metaschema
- [x] Create a metaschema to XML pipeline with the capabilities needed to write an equivalent metaschema xml definition
- [x] Create tests demonstrating the parser functionality (#2)

As of 8/1/22 this issue has the following sub-issues:
- [x] #19
- [x] #20
- [x] #21
