### ISSUE TITLE
Metaschema codegen

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/metaschema-node#14]
# User Story:

As a Metaschema user, I want an efficient way to generate Typescript classes from Metaschema XML definitions

## Goals:

- [ ] An approach is chosen for generating Typescript and documented as an ADR entry
- [ ] Capability to emit Typescript classes from a metaschema
- [ ] CLI tool to streamline development

## Dependencies:

This epic depends on the completion of the last epic, defining a basic working implementation of the metaschema object model: #5
