### ISSUE TITLE
Metaschema codegen binding parser

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/metaschema-node#15]
# User Story:

As a Metaschema developer, I need my generated Metaschema classes to have the ability to save and load XML, JSON, and YAML.

## Goals:

- [ ] An approach for the bound XML, JSON, and YAML parsing is chosen and documented as an ADR entry
- [ ] Implementation for bound classes for the relevant object models
- [ ] Creation of the binding parser capable of (de)serializing bound classes
- [ ] Adjustment to the generated classes of #14 to use the binding decorators

## Dependencies:

The code generation for the basic classes must be complete: #14
